# Generated by Django 3.1.6 on 2021-02-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagramelement',
            options={},
        ),
    ]
