# Generated by Django 3.1.6 on 2021-02-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20210204_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramelement',
            name='element_name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
